run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Code style
    - gofmt
    - goimports
    - misspell
    - whitespace

    # Code quality
    - unconvert
    - unparam
    - prealloc
    - bodyclose
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

    # Error handling
    - errorlint

    # Security
    - gosec

    # Performance
    - gocritic

    # Complexity
    - gocyclo
    - gocognit
    - cyclop
    - maintidx

    # Best practices
    - revive
    - goconst
    - gomoddirectives
    - durationcheck
    - errname
    - forcetypeassert

    # Documentation
    - godot

    # Testing
    - tparallel
    - testableexamples

linters-settings:
  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'

  goimports:
    local-prefixes: github.com/gofhir/validator

  misspell:
    locale: US

  govet:
    enable-all: true
    disable:
      - fieldalignment # Too noisy
      - shadow

  gocyclo:
    min-complexity: 20

  gocognit:
    min-complexity: 30

  cyclop:
    max-complexity: 20
    skip-tests: true

  maintidx:
    under: 20

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy

  gosec:
    excludes:
      - G104 # Audit errors not checked
      - G304 # File path provided as taint input

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        arguments:
          - "checkPrivateReceivers"
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  godot:
    scope: toplevel
    capital: true

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-use-default: false

  exclude-rules:
    # Test files have relaxed rules
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - cyclop
        - maintidx
        - goconst
        - errcheck
        - gosec
        - forcetypeassert

    # Allow fmt.Fprintf to stderr in loader
    - path: pkg/loader/
      linters:
        - errcheck
      text: "Error return value of `fmt.Fprintf` is not checked"

    # Allow package comments to not end with period in main packages
    - path: cmd/
      linters:
        - godot

  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
  fix: false

severity:
  default-severity: warning
  case-sensitive: false
  rules:
    - linters:
        - gosec
      severity: error
    - linters:
        - errcheck
      severity: error
