run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - dogsled
    - dupl
    - copyloopvar
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - stylecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 150

  goconst:
    min-len: 5
    min-occurrences: 4

  misspell:
    locale: US

  goimports:
    local-prefixes: github.com/gofhir

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        - errcheck
        - gocyclo

    - path: doc\.go
      linters:
        - stylecheck

    # Exclude gochecknoinits from funcs package (init functions for registration)
    - path: "funcs/.*\\.go"
      linters:
        - gochecknoinits

    # Exclude gochecknoinits from pool.go
    - path: "types/pool\\.go"
      linters:
        - gochecknoinits

    # Exclude gocyclo from temporal types
    - path: "types/(datetime|date|time)\\.go"
      linters:
        - gocyclo

    # Exclude gocyclo from evaluator
    - path: "eval/evaluator\\.go"
      linters:
        - gocyclo

    - path: "funcs/math\\.go"
      linters:
        - gocyclo

    - path: "funcs/fhir\\.go"
      linters:
        - gocyclo

  max-issues-per-linter: 50
  max-same-issues: 10
