#!/usr/bin/env bash
# Rebuild testdata/m12-slice-scoping/decisions/instances and packages/acme.decisions-<VERSION>.tgz.
#
# The package ships snapshots generated by the HL7 validator from the differentials, so both
# validators consume identical definitions and neither one's snapshot generator affects the probes.
#
# Usage: tools/build_acme_decisions.sh /path/to/validator_cli.jar
set -euo pipefail

VERSION="0.3.0" # keep in step with gen_acme_decisions.py
JAR="${1:?usage: $0 /path/to/validator_cli.jar}"
JAR="$(cd "$(dirname "$JAR")" && pwd)/$(basename "$JAR")" # absolute: java runs from a temp dir
HERE="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

python3 "$HERE/tools/gen_acme_decisions.py" "$WORK" >/dev/null

# The profiles reference each other (mm-profile -> pat-p1/pat-p2, slices -> ext-a), so the
# differentials are also offered to HL7 as a package.
mkdir -p "$WORK/diffpkg/package"
cp "$WORK"/defs/*.json "$WORK/diffpkg/package/"
printf '{"name":"acme.decisions","version":"%s","fhirVersions":["4.0.1"],"dependencies":{"hl7.fhir.r4.core":"4.0.1"}}\n' \
  "$VERSION" >"$WORK/diffpkg/package/package.json"
tar -czf "$WORK/diff.tgz" -C "$WORK/diffpkg" package

(cd "$WORK" && java -jar "$JAR" snapshot defs/StructureDefinition-*.json -outputSuffix snapshot.json \
  -version 4.0.1 -tx n/a -ig diff.tgz >snapshot.log 2>&1) || {
  tail -20 "$WORK/snapshot.log" >&2
  exit 1
}

mkdir -p "$WORK/pkg/package"
for f in "$WORK"/defs/*.json; do
  base="$(basename "$f")"
  [[ "$base" == *.snapshot.json ]] && continue
  case "$base" in
  StructureDefinition-*) cp "$f.snapshot.json" "$WORK/pkg/package/$base" ;;
  *) cp "$f" "$WORK/pkg/package/$base" ;;
  esac
done
cp "$WORK/diffpkg/package/package.json" "$WORK/pkg/package/"

# Every StructureDefinition must carry a snapshot, or the package is not what it claims to be.
python3 - "$WORK/pkg/package" <<'PY'
import glob, json, sys
missing = [p for p in glob.glob(sys.argv[1] + "/StructureDefinition-*.json")
           if not json.load(open(p)).get("snapshot", {}).get("element")]
if missing:
    sys.exit("no snapshot in: " + ", ".join(missing))
PY

tar -czf "$HERE/packages/acme.decisions-$VERSION.tgz" -C "$WORK/pkg" package
rm -rf "$HERE/decisions/instances"
cp -r "$WORK/instances" "$HERE/decisions/instances"
echo "built packages/acme.decisions-$VERSION.tgz and decisions/instances"
